### ISSUE TITLE
Add option to interpolate variable for "pwd"

### ISSUE THREAD

**Issue by hangtwenty** [briangonzalez/termrc#12]
For projects like [this one](https://github.com/callistaenterprise/blog-microservices) — Termfile committed to a git repository — it makes sense to have Termfiles where you can set `root` to be relative to the present working directory (wherever you run `termrc`). Maybe there could be a variable like `$pwd` that gets interpolated. Or just `.`.

```
root:
  ./microservices
```

I haven't worked with AppleScript before but I'll try to remember, and submit a PR. Adding this issue just as a reminder to myself really!

Thanks for a really useful tool ^__^

**Comment by briangonzalez** [comment]
Project moved and rewritten here with iTerm2 3.0.0 support: https://github.com/eggplanetio/mert
