### ISSUE TITLE
error on even single pane

### ISSUE THREAD

**Issue by eashman** [briangonzalez/termrc#13]
getting this error on even just a single pane start.

I am using the latest nightly of iTerm2 so if that's it, there may be a major incompatibility brewing.
```
╰─$ termrc start
** Starting termrc using: 'Termfile'
** Please wait until all panes have fully launched!
/var/folders/wf/df8bxtf514gggj7tz5k6686h0000gn/T/termrc.osascript20150823-10209-1lt1ob3:714:717: script error: Expected end of line, etc. but found “the”. (-2741)
```

my Termfile:

```
commands:
  here: echo "Hello, here."

layout:
  - [ here ]
```

**Comment by briangonzalez** [comment]
@eashman Is this still happening? Also, which OS and Ruby version?

**Comment by jadb** [comment]
I confirm this is still happening.

```
~❯ termrc start
** Starting termrc using: 'Termfile'
** Please wait until all panes have fully launched!
/tmp/termrc.osascript20150907-22293-eu2pv0:1150:1153: script error: Expected end of line, etc. but found “the”. (-2741)
```

Using the default `Termfile` created by `termrc create`, running nightly iTerm2.

**Comment by jadb** [comment]
Works fine on the stable iTerm version.

**Comment by jadb** [comment]
Sorry for the flood of issues, but thought I'd include some more details:

```
~❯ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
~❯ sw_vers -productVersion
10.10.4
```

**Comment by vitalybe** [comment]
There is been a change in the scripting language in the last versions, it is probably what's causing the issue

**Comment by briangonzalez** [comment]
@vitalybe Would you have a second to check and determine what I am doing wrong?

**Comment by vitalybe** [comment]
I'll try to get to it in a while. However, the gist of the change is that "terminal" keyword is no longer valid. The change is described [here](https://www.iterm2.com/applescript.html).

So [this](https://gist.github.com/bobthecow/757788):

      tell application \"iTerm\"
        tell current terminal
          launch session \"Default Session\"
          tell the last session
            write text \"cd \\\"$cdto\\\"$cmd\"
          end tell
        end tell
      end tell

Became [this](https://gist.github.com/vitalybe/021d2aecee68178f3c52):

        tell application "iTerm"
            tell current window
                set newTab to (create tab with default profile)
                tell newTab
                    tell current session
                        write text "cd \"$cdto\"$cmd"
                    end tell
                end tell
            end tell
        end tell

**Comment by vitalybe** [comment]
I looked on it a bit more and it seems that a lot has changed. I've changed a script to server as a guideline to code change. For example this YAML:

```
commands:
  here:       echo "Hello, here."
  there:      echo "Hello, there."
  world:      echo "Hello, world."
  me:         echo "Hello, me."
  you:        echo "Hello, you."

layout:
  - [ here, there ]       # row 1, with 2 panes
  - [ world ]             # row 2, with 1 pane
  - [ me, you ]           # row 3, with 2 panes
```

Generated today the [following code](https://gist.github.com/vitalybe/d19087e383135557ea1a). I rewrote it to work with latest version of iTerm2. The new code is not only shorter, but is also a lot more reliable since it doesn't rely on key presses and sleeps. It looks like so:

```
tell application "iTerm"
	tell first window
		set newTab to (create tab with default profile)
		tell newTab
			-- creating rows
			tell current session
				split horizontally with default profile
				split horizontally with default profile
			end tell
			
			set row1_col1 to (item 1 of sessions)
			set row2_col1 to (item 2 of sessions)
			set row3_col1 to (item 3 of sessions)
			
			-- creating columns
			tell row1_col1
				set row1_col2 to (split vertically with default profile)
			end tell
			
			tell row3_col1
				set row3_col2 to (split vertically with default profile)
			end tell
			
			-- running commands
			tell row1_col1 to write text "echo Hello here"
			tell row1_col1 to set name to "here"
			tell row1_col2 to write text "echo Hello there"
			tell row1_col2 to set name to "there"
			
			tell row2_col1 to write text "echo Hello world"
			tell row2_col1 to set name to "world"
			
			tell row3_col1 to write text "echo Hello me"
			tell row3_col1 to set name to "me"
			tell row3_col2 to write text "echo Hello you"
			tell row3_col2 to set name to "you"
			
		end tell
	end tell
end tell
```

The next step is to change `builder.rb` for the new code. I might do it, but that won't happen soon.

**Comment by briangonzalez** [comment]
Project moved and rewritten here with iTerm2 3.0.0 support: https://github.com/eggplanetio/mert
