### ISSUE TITLE
Not working on latest iTerm2 build 3.0.0

### ISSUE THREAD

**Issue by jcreencia** [briangonzalez/termrc#22]
Showing this error on termrc start:

/var/folders/6p/n81140xs6hb1nzdj34slhbkh0000gn/T/termrc.osascript20160603-24390-mwfoi4:1129:1133: execution error: iTerm got an error: Can’t get terminal 2. Invalid index. (-1719)

**Comment by briangonzalez** [comment]
Project moved and rewritten here with iTerm2 3.0.0 support: https://github.com/eggplanetio/mert
