### ISSUE TITLE
First row never split 

### ISSUE THREAD

**Issue by LeonardoGentile** [briangonzalez/termrc#5]
First of all Thanks! This project is amazing ! :thumbsup:

If I specify multiple rows then the panes will be split only on the last row, never on the first, second and so on.
As of your example:
```
commands:
  here:       echo "Hello, here."
  there:      echo "Hello, there."
  world:      echo "Hello, world."
  me:         echo "Hello, me."
  you:        echo "Hello, you."

layout:
  - [ here, there, here ]       # row 1, with 3 panes
  - [ me, you ]           # row 2, with 2 panes
  - [ me, you ]           # row 3, with 2 panes
```
this will produce 3 rows, the first 2 containing only one pane (_here_ on the first row, _there_ on the second row) while the third will have 5 panes (here, me, you, me, you).

The order is preserved tough

**Comment by magnus-larsson** [comment]
Hello Brian!

Did you get time to look into this issue?

I really like termrc as well but I have the same annoying problem as reported by Leonardo.

Regards,
Magnus.

**Comment by briangonzalez** [comment]
Hi magnus -- would you mind taking a first pass and try to diagnose the issue?

**Comment by magnus-larsson** [comment]
Hello Brian!

Sure, but I don't really know how to proceed,
I'm not a Ruby developer (Java and C# works fine for me :-)

Can you give me some intro on how to diagnose the issue?

Mvh,
Magnus.
--
Magnus Larsson

Callista Enterprise AB
mobile: +46 (0)733-51 91 72
mailto:magnus.larsson@callistaenterprise.se
http://www.callistaenterprise.se

**Comment by briangonzalez** [comment]
Hi Magnus:

I'd first start by tinkering with `SLEEP_INTERVAL` - https://github.com/briangonzalez/termrc/blob/master/lib/termrc/builder.rb#L9

Once you've made your changes, you can try them within the project:

`./bin/termrc lib/template/termfile_columns.template`

**Comment by magnus-larsson** [comment]
Ok, thanks!

I'll try this, but how dow I build termrc from source?

I have no previous knowledge in Ruby development :-(

I have performed "git clone git@github.com:briangonzalez/termrc.git", but
now I'm stuck...

Regards,
Magnus.
--
Magnus Larsson

Callista Enterprise AB
mobile: +46 (0)733-51 91 72
mailto:magnus.larsson@callistaenterprise.se
http://www.callistaenterprise.se

**Comment by briangonzalez** [comment]
There is no "build from source", since ruby is interpreted. You'll want to make your edits, then run `./bin/termrc lib/template/termfile_columns.template`

**Comment by magnus-larsson** [comment]
Hello again Brian!

I changed  SLEEP_INTERVAL  from 1 to 10 to be able to see its impact and
then I run the command:

./bin/termrc start lib/template/termfile.template

First the following four panes are drawn:

[image: Inline image 1]
Then after 10 sec that following panes are drawn:

[image: Inline image 2]
Not resulting in the expected (from your docs):

[image: Inline image 3]
Any idea of what is going wrong?
Can you repeat this behaviour?

Regards,
Magnus.
--
Magnus Larsson

Callista Enterprise AB
mobile: +46 (0)733-51 91 72
mailto:magnus.larsson@callistaenterprise.se
http://www.callistaenterprise.se

**Comment by briangonzalez** [comment]
Closing for now due to the age of this issue.

**Comment by LeonardoGentile** [comment]
well ok but still happening :)

**Comment by briangonzalez** [comment]
Mind helping debug? I'd love to get this fixed, but don't have a machine this is currently broken on.

**Comment by LeonardoGentile** [comment]
Sure, how can I help you?
I'm on OsX 10.9.5 and iterm2 build `1.0.0.20130622`
