### ISSUE TITLE
Open in new tab rather than new window

### ISSUE THREAD

**Issue by LeonardoGentile** [briangonzalez/termrc#8]
Is it possible to specify if the panes should be opened in a new tab or a new window?
Right now as default  it seems that a new window is created all the times.

**Comment by briangonzalez** [comment]
Yes, it is. See read me.

**Comment by briangonzalez** [comment]
Oh, you mean within the current window. Not supported yet. PR's welcome.

**Comment by LeonardoGentile** [comment]
@briangonzalez yes, I meant within the current window, I would do it myself but I'm not really a ruby developer, I'll try to look at the code and figure out what I could do depending from what I'll understand

Thank you
